project:
  type: website

website:
  title: "claudio"
  twitter-card: true
  site-url: https://blog.claudiogoncalves.me
  description: "Personal blog of Claudio Gonçalves"
  search: 
    location: navbar
    type: textbox
  navbar:
    background: "slategray"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cvgoncalves
      # - icon: twitter
      #   href: https://twitter.com/GoncalvesCv
format:
  html:
    theme: 
      light: spacelab
      dark: solar




