project:
  type: website

website:
  title: "claudio"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    # background: "lightgreen"
    right:
      - about.qmd
      # - today_i_learned.qmd
      - rpg.qmd
      - icon: github
        href: https://github.com/cvgoncalves
      - icon: twitter
        href: https://twitter.com/GoncalvesCv
format:
  html:
    theme: 
      light: spacelab
      dark: darkly
    css: styles.css



