title: Notre-Dame de Paris
baseURL: https://gohugo-theme-ananke.pages.dev
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Ananke
    weight: 1
  fr:
    contentDir: content/fr
    title: Ananke Fr
    weight: 2
  br:
    contentDir: content/br
    title: Ananke Br
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/GoncalvesCv
    - name: github
      url: https://github.com/cvgoncalves
    - name: mastodon
      url: https://noc.social/@gon
      rel: me noopener
    - name: linkedin
      url: https://www.linkedin.com/in/cvgoncalves/
    # - name: kaggle
    #   url: https://www.kaggle.com/cvgoncalves
  author: ''
  background_color_class: bg-black
  description: The last theme you'll ever need. Maybe.
  favicon: ''
  recent_posts_number: 3
  site_logo: ''
  text_color: ''
